apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: ram-ns-label-opa-template
  project: giri-prod-test
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/ram-ns-label-opa-template/ns-label-opa-template.yaml
    options: {}
    type: Yaml
