apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apps
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCJugzSAS+iN6JQ/jy5CySvvgE9zCNCkJG7anoFyRYyg1QZ2MSWJD/P30KJo0+R9j6qZAcwvff7B9RTQI4pKlJ1/ljDC+39zUJ3ok/Ddy9bBlBVAW8SPH73/EkGxilCePmqW6GSnSCZj8m/cw/W3IV2N6G03yXczbVYzcHkmxG88DE3Twmdz8AFx3d0leqB7AncKdHBMc0Ww6M7advWFjSWxwLaracIMsydqDTKFmGzmHFyq7f8aI1DRVhi7gX0dZ7MduS7COKLYooQe4RDMc7/XnfH0bVOJ7c/NSfuBjVFF++weN4LidNNMis2U2qIzXD61lF9iFaijmxOEBZziwyltiWi8gD9uvu75OIFL7tg5O7xeDHWoH9TkqQ2eeAseqPlHGA/N+DpdmY6+y4E8XUjZyg6Tg0SEqE=
  template:
    metadata:
      creationTimestamp: null
      name: apps
      namespace: default

