apiVersion: security.k8smgmt.io/v3
kind: ClusterNetworkPolicyRule
metadata:
  name: july-01-xwing-block-crule
  project: giri-prod-test
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/july-01-xwing-block-crule/standard_cilium_networkpolicy.yaml
    options: {}
    type: Yaml
  version: v2
