apiVersion: security.k8smgmt.io/v3
kind: ClusterNetworkPolicyRule
metadata:
  name: may-cluster-xwing
  project: giri-prod-test
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/may-cluster-xwing/cluster-wide-rule.yaml
    options: {}
    type: Yaml
  version: xwing-block
