apiVersion: security.k8smgmt.io/v3
kind: NetworkPolicyProfile
metadata:
  name: december-profile
  project: giri-prod-test
spec:
  installationParams:
    policyEnforcementMode: default
  version: v1
