apiVersion: cost.k8smgmt.io/v3
kind: CostProfile
metadata:
  name: giri-aks
  project: giri-prod-test
spec:
  installationParams:
    azure:
      customPricing:
        cloudCredentialsName: aks-cost
  providerType: azure
  version: v1
