apiVersion: cost.k8smgmt.io/v3
kind: CostProfile
metadata:
  name: rctl-onprem1-del
  project: giri-prod-test
spec:
  installationParams:
    other:
      cpu: "0.2"
      gpu: "0.5"
      memory: "0.2"
  providerType: other
  version: onprem-version1
