apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: b
  project: giri-prod-test
spec:
  base:
    name: default
    version: 1.25.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
