apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: eks-bp
  project: giri-prod-test
spec:
  base:
    name: default
    version: 1.23.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  networkPolicy:
    profile:
      name: default
      version: latest
  type: custom
  version: v1
