apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: giri-bp1-rctlv3
  project: giri-prod-test
spec:
  base:
    name: default-aks
    version: 1.25.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: sdasd
