apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: helm
  project: giri-prod-test
spec:
  base:
    name: default
    version: 1.25.0
  customAddons:
  - name: helm-addon1
    version: v3
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v2
