apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: jan-old
  project: giri-prod-test
spec:
  base:
    name: default-aks
    version: 2.3.0
  costProfile:
    name: default-cost-profile-azure
    version: version-1705725305
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  networkPolicy:
    policies:
    - name: dec13-p1
      version: v1
    profile:
      name: default
      version: latest
  opaPolicy:
    opaPolicy:
    - name: policy-privileged
      version: version-1705214554
    profile:
      name: default
      version: latest
  type: custom
  version: new-v4
