apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: minim
  project: giri-prod-test
spec:
  base:
    name: minimal
    version: 1.25.0
  defaultAddons:
    enableMonitoring: true
  driftWebhook:
    enabled: true
  networkPolicy:
    policies:
    - name: may-policy
      version: v1
    profile:
      name: default
      version: latest
  type: custom
  version: v1
