apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: nov-custom
  project: giri-prod-test
spec:
  base:
    name: nov-gold
    version: v1
  customAddons:
  - name: may18-xwing
    version: version1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  type: custom
  version: v1
