apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nov-nginx
  project: giri-prod-test
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nov-nginx/nginx-15.4.2.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: nov-nginx
  placement:
    selector: rafay.dev/clusterName=giri-prod-nov5
  version: nov-nginx-v1-202411050812200000
