apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: sample-app
  project: giri-prod-test
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/sample-app/sample-app.yaml
    type: Yaml
  namespace: cilium-test
  placement:
    selector: rafay.dev/clusterName=giri-mar-old
  version: sample-app-v1-202403020628030000
