apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: tomcat-app
  project: giri-prod-test
spec:
  artifact:
    artifact:
      chartName: tomcat
      chartVersion: 11.0.1
      repository: default-bitnami
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: tomcat
  placement:
    selector: rafay.dev/clusterName=giri-prod-apr16
  version: tomcat-app-v1-202404161608180000
