apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: giri-prod
  project: giri-prod-test
spec:
  active: true
  stages:
  - config:
      destinationRepo: {}
      excludedResources:
      - name: Cluster
      - name: InfraProvisioner
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        repository: giri-prod
        revision: main
      systemToGitSync: true
    name: test
    type: SystemSync
  triggers:
  - config:
      repo:
        provider: Github
        repository: giri-prod
        revision: main
    name: test
    type: Webhook
