apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: nginx-replica
  project: giri-prod-test
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx-replica/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/nginx-replica/valuse-2rep.yaml
      - name: file://artifacts/nginx-replica/values.yaml
    type: Helm
  namespace: giri-nginx-test
  sharing: {}
  version: v4-3rep
