apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: nginx
  project: giri-prod-test
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/nginx/values.yaml
    type: Helm
  namespace: prod-xwing
  sharing: {}
  version: v2
