apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  annotations:
    rafay.dev/audit_type: BROWSER||Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
      AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
    rafay.dev/audit_user: giridharaprasad@rafay.co
    rafay.dev/audit_user_group: Organization Admins
  name: nov-addon-xwing
  project: giri-prod-test
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nov-addon-xwing/jenkins-9.0.0.tgz
    type: Helm
  namespace: nov-addon
  sharing: {}
  version: v1
